name: Deploy to Production

on:
  push:
    branches:
      - main # Trigger on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Production VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PROD_SSH_HOST }}
        username: ${{ secrets.PROD_SSH_USERNAME }}
        key: ${{ secrets.PROD_SSH_KEY }}
        script: |
          echo "Deploying frontend..."
          # Frontend Deployment: Replace /var/www/html with new frontend files
          # Assuming frontend files are in the 'frontend' directory of the repo
          sudo rm -rf /var/www/html/*
          sudo cp -r ${{ github.workspace }}/frontend/* /var/www/html/

          echo "Deploying backend..."
          # Backend Deployment: Replace /opt/sep-backend with new backend files
          # Assuming backend files are in the 'backend' directory of the repo
          sudo rm -rf /opt/sep-backend/*
          sudo cp -r ${{ github.workspace }}/backend/* /opt/sep-backend/

          echo "Installing backend dependencies..."
          # Install backend dependencies
          cd /opt/sep-backend
          npm install --production

          echo "Restarting backend service..."
          # Restart backend service (assuming systemd service named 'sep-backend')
          sudo systemctl daemon-reload
          sudo systemctl restart sep-backend
          sudo systemctl status sep-backend
