name: Promote to Prod

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  promote-prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Download latest release artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: release.yaml
          workflow_conclusion: success
          name: release-build
          path: ./release

      - name: Extract artifact
        run: tar -xzf ./release/app.tar.gz -C ./release

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Deploying frontend (version ${{ env.VERSION }})..."
            sudo rm -rf /opt/sep-business/frontend/*
            sudo cp -r $GITHUB_WORKSPACE/release/frontend/* /opt/sep-business/frontend/

            echo "Deploying backend..."
            sudo rm -rf /opt/sep-business/backend/*
            sudo cp -r $GITHUB_WORKSPACE/release/backend/* /opt/sep-business/backend/

            echo "Installing backend dependencies..."
            cd /opt/sep-business/backend/
            npm install --production

            echo "Restarting backend service..."
            sudo systemctl daemon-reload
            sudo systemctl restart sep-business-backend
            sudo systemctl status sep-business-backend
