name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: release
  cancel-in-progress: true
  
jobs:
  release:
    name: 🏷️ Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semrel.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Semantic Release - Official Version
        id: semrel
        uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  deploy-prod:
    name: 🚀 Deploy (Production)
    needs: release
    uses: ./.github/workflows/_build-and-deploy.yaml
    with:
      environment: prod
      version: ${{ needs.release.outputs.version }}
    secrets: inherit