name: Release & Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/release.yaml'

permissions:
  contents: write

concurrency:
  group: release
  cancel-in-progress: true
  
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run semantic release
        uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-file: package.json


  deploy-dev:
    needs: release
    uses: ./.github/workflows/_build-and-deploy.yaml
    with:
      environment: dev
    secrets: inherit

  promote-prod:
    needs: deploy-dev
    uses: ./.github/workflows/_build-and-deploy.yaml
    with:
      environment: prod
    secrets: inherit